### 获取所有用户
GET http://localhost:9876/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag

### 登录
POST http://localhost:9876/api/login
Content-Type: application/json

{
  "username": "test2",
  "password": "test2"
}

### 登录
POST http://49.234.40.111:23334/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### 根据用户ID选择用户
GET http://localhost:9876/api/user/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag

### 添加用户
POST http://localhost:9876/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag
Content-Type: application/json

{
  "username": "test2",
  "password": "test2",
  "type": 1
}

### 修改用户
PATCH http://localhost:9876/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag
Content-Type: application/json

{
  "id": 3,
  "username" :"test3"
}

### 删除用户
DELETE http://localhost:9876/api/user/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag


### 查询订单
GET http://localhost:9876/api/order/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTYxMTAwNjgsImlhdCI6MTU5NTUwNTI2OCwic3lzdGVtSWQiOjQsInVzZXJuYW1lIjoidGVzdDIiLCJ0eXBlIjoxfQ.0fxWvN7_V9-x3zp3NJGQxgjuBp6WqB6ygrAFsq5kFHo

### 查询单个订单
GET http://localhost:9876/api/order/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag

### 删除订单
DELETE http://localhost:9876/api/order/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag

### 添加订单
POST http://localhost:9876/api/order
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTU3NDczNjYsImlhdCI6MTU5NTE0MjU2Niwic3lzdGVtSWQiOjQsInVzZXJuYW1lIjoidGVzdDIiLCJ0eXBlIjoxfQ.ZX9t09luZt5v8MsvC6fI4uZR3V5J25KeYlYknQkyXKU

{
  "customer_name": "招商银行",
  "file_name": "zhaoshang.jpg",
  "department": "铁皮部",
  "material_id": [1,2,3],
  "maker_id": 1,
  "process": ["铁皮字","打孔字"],
  "deadline_time":1595142814,
  "origin_amount": 100.01,
  "discount": 0.5
}

###Tes
POST http://localhost:9876/api/demo
Content-Type: application/json

{
  "customer_name": "招商银行",
  "file_name": "zhaoshang.jpg",
  "department": "铁皮部",
  "material_id": [1,2,3],
  "maker_id": 1,
  "process": ["铁皮字","打孔字"],
  "deadline_time":"2020-01-02",
  "origin_amount": 100.01,
  "discount": 0.5
}

###
PATCH http://localhost:9876/api/order
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTU3NDczNjYsImlhdCI6MTU5NTE0MjU2Niwic3lzdGVtSWQiOjQsInVzZXJuYW1lIjoidGVzdDIiLCJ0eXBlIjoxfQ.ZX9t09luZt5v8MsvC6fI4uZR3V5J25KeYlYknQkyXKU

{
  "system_id": 3,
  "deadline_time":1595142814
}

###
GET http://49.234.40.111:23334/api/eff/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag

### 修改订单状态
PATCH http://localhost:9876/api/order/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag
Content-Type: application/json

{
  "system_id": 6,
  "admin_status": 0
}

### 修改订单完成状态
PATCH http://localhost:9876/api/order/status
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTQyODgyODUsImlhdCI6MTU5MzY4MzQ4NSwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOjF9.iOa9JrMdWLyVx4o69kWKjYxDDwGN_63VCrYlPugrjag
Content-Type: application/json

{
  "system_id": 6,
  "order_status": 0
}

