### 登录
POST http://localhost:23334/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTYxOTQ5MjUsImlhdCI6MTU5NTU5MDEyNSwic3lzdGVtSWQiOjQsInVzZXJuYW1lIjoidGVzdDIiLCJ0eXBlIjoxfQ.ElUUIZEean3YcUk2jC1RnkWB6dw7PFluTEZ5KEDaliI

### eff
GET http://localhost:23334/api/eff/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTcyNDU2OTYsImlhdCI6MTU5NjY0MDg5Niwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.4TgvM1C0Bb2rxn4TbnSYpsWgToqzEAAjQzeSpNskT-M
### 用户列表
GET http://localhost:9876/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTYxOTQ5MjUsImlhdCI6MTU5NTU5MDEyNSwic3lzdGVtSWQiOjQsInVzZXJuYW1lIjoidGVzdDIiLCJ0eXBlIjoxfQ.ElUUIZEean3YcUk2jC1RnkWB6dw7PFluTEZ5KEDaliI

### 单个用户
GET http://localhost:9876/api/user/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTYxOTQ5MjUsImlhdCI6MTU5NTU5MDEyNSwic3lzdGVtSWQiOjQsInVzZXJuYW1lIjoidGVzdDIiLCJ0eXBlIjoxfQ.ElUUIZEean3YcUk2jC1RnkWB6dw7PFluTEZ5KEDaliI

### 添加订单
POST http://localhost:23334/api/order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U
Content-Type: application/json

{
  "customer_name": "招商银行",
  "file_name": "zhaoshang.jpg",
  "department": "铁皮部",
  "material": [
    {
      "material_id": 1,
      "material_num": 10
    },
    {
      "material_id": 4,
      "material_num": 10
    }
  ],
  "maker_id": 4,
  "process": ["铁皮字","打孔字"],
  "deadline_time": 1595142814,
  "origin_amount": 100.01,
  "discount": 0.5
}

### 订单列表
GET http://localhost:23334/api/order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTcxNTQ5NTYsImlhdCI6MTU5NjU1MDE1Niwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.U6eEhB-BYF9wgQ3-J-eIwiyYePe81MfXuWgS-KCOIjI

### 绩效列表
GET http://localhost:23334/api/eff/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U


### 单个订单列表
GET http://localhost:23334/api/order/8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U


### 删除订单
DELETE http://localhost:23334/api/order/8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U

### 修改订单
PATCH http://localhost:23334/api/order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U
Content-Type: application/json

{
"system_id": 9,
"customer_name": "招商银行",
"file_name": "zhaoshang.jpg",
"department": "铁皮部",
"material": [
{
"material_id": 1,
"material_num": 10
},
{
"material_id": 4,
"material_num": 11
}
],
"maker_id": 1,
"process": [
"打孔字"
],
"deadline_time": 1595142814,
"order_status": 0,
"admin_status": 0,
"origin_amount": 100.01,
"discount": 0.5,
"amount": 50.005
}


### 订单审核
PATCH http://localhost:23334/api/order/admin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U
Content-Type: application/json

{
  "system_id" : 9,
  "admin_status" : 1
}

### 订单完成
PATCH http://localhost:23334/api/order/status
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U
Content-Type: application/json

{
  "system_id" : 9,
  "order_status" : 1
}

### 财务列表
GET http://localhost:23334/api/fund
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U

### 修改财务
PATCH http://localhost:23334/api/fund
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U
Content-Type: application/json

{
  "system_id" : 6,
  "fund_type" : -1
}

### 修改财务
POST http://localhost:23334/api/fund
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTY4NzY5OTEsImlhdCI6MTU5NjI3MjE5MSwic3lzdGVtSWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJ0eXBlIjoxfQ.yNUUVD2LTWLGDctf71yCQf2hnqxVirSfInsSbbvI2-U
Content-Type: application/json

{
  "name": "房租",
  "fund_type" : -1,
  "amount": 100
}